version: "3.9"

services:
  dev:
    build:
      context: ./app
      dockerfile: .dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./app/dist:/app/dist
    ports:
      - "3000:3000"
    # command: [sh, -c, "npm install && npm run dev"]
    command: ["npm", "run", "dev"]

  github-deploy:
    build:
      context: ./githubPages
      dockerfile: .dockerfile
    volumes:
      - .:/app
      - /app/app/node_modules
      - ./app/dist:/app/app/dist
    working_dir: /app/app
    command: ["npm", "run", "github-deploy"]

  test:
    build:
      context: ./app
      dockerfile: .dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    command: ["npm", "test"]

  prod:
    build:
      context: ./production
      dockerfile: .dockerfile
    volumes:
      - ./app/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - dev

volumes:
  dist-volume: